In [128]:
import tensorflow as tf
import os
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers,optimizers,datasets
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # or any {'0', '1', '2'}

In [9]:
class GCN(keras.Model):
    def __init__(self, input_dim, output_dim, num_feature_nonzero, **kwargs):
        super(GCN,self).__init__(**kwarges)
        
        self.input_dim =input_dim
        self.output_dim = output_dim

        self.layers_ = []
        self.layers_.append(GraphConvolution(input_dim=self.input_dim,
                                            output_dim=args.hidden1,
                                            num_feature_nonzero = num_feature_nonzero,
                                            activation=tf.nn.relu,
                                            dropout=args.dropout,
                                            is_sparse_inputs=True))
        self.layers_.append(GraphConvolution(input_dim=args.hidden1, # 16
                                            output_dim=self.output_dim, # 7
                                            num_features_nonzero=num_features_nonzero,
                                            activation=lambda x: x,
                                            dropout=args.dropout))
        for p in self.trainable_variables:
            print(p.name,p.shape)
            
    def call(self,inputs,training=None):
        x,label,mask,support = inputs
        outputs = [x]
        
        for layer in self.laysers:
            hidden = layer((outputs[-1],support),training)
            output.append(hidden)
        output = outputs[-1]
        
        loss = tf.zeros([])
        for var in self.layers_[0].trainable_variables:
            loss += args.weight_decay * tf.nn.l2_loss(var)
        
        loss += maskdf_soft_max_cross_entroy
        acc= masked_accuracy(output,label,mask)
        
        return loss,acc
    
    def predict(self):
        return tf.nn.softmax(self.output)
        

In [12]:
class MLP(keras.Model):
    def __init__(self,placeholders,input_dim,**kwargs):
        super(MLP,self)._init__(**kwargs)
        self.inputs = placeholders['features']
        self.input_dim = input_dim
        self.output_dim = placeholders['labels'].get_shape().as_lsit()[1]
        self.placeholders =placeholders
        self.optimizer = tf.train.AdamOptimizer(learn_rate=args.learning_rate)
        self.build()
    
    def _loss(self):
        for var in self.layers[0].vars.values():
            self.loss += args.weight_decay * tf.nn.ls_loss(var)
        
        self.loss += masked_softmax_coss_entropy(self.outputs,self.placeholders['labels'],self.placeholders['labels_mask'])
    
    def _build(self):
        self.layers.append(Dense(input_dim=self.input_dim,
                                output_dim =self.args.hidden1,
                                placeholders=self.placeholders,
                                 act = tf.nn.relu,
                                 dropout = True,
                                 logging = self.logging
                                ))
    def predict(self):
        return tf.nn.softmax(self.outputs)
    

        
            

SyntaxError: unexpected EOF while parsing (<ipython-input-12-3b10f777e68a>, line 12)

In [15]:
class Dense(layers.Layer):
    def __init__(self,input_dim,output_dim,placeholders,dropout=0.,sparse_inputs=False,act=tf.nn.relu,bias=False,featureless=False,**kwargs):
        super(Dense,self)._init__(**kwargs)
        if dropout:
            self.dropout = placehole['dropout']
        else:
            self.dropout = 0.
        
        self.act = act
        self.sparse_inputs = sparse_inputs
        self.featureless = featureless
        self.bias = bias
        
        self.num_features_nonzero =placeholders['num_features_nonzero']

class GraphConvolution(layers.Layer):
    
    def __init__(self, input_dim, output_dim, num_features_nonzero,
                 dropout=0.,
                 is_sparse_inputs=False,
                 activation=tf.nn.relu,
                 bias=False,
                 featureless=False, **kwargs)
        super(GraphConvolution,self).__init__(**kwargs)

        self.dropout = dropout
        self.activation = activation
        self.is_sparse_inputs = is_sparse_inputs
        self.featureless = featureless
        self.bias = bias
        self.num_features_nonzero = num_features_nonzero

        self.weights_=[]

        for i in range(1):
            w = self.add_variable('weight'+str(i),[input_dim,output_dim])
            self.weights_.append(w)
        if self.bias:
            self.bias = self.add_variable('bias',[output_dim])
    
    
    def call(self,inputs,training=None):
        s, support_=inputs
        if training is not False and self.is_sparse_inputs:
            x = sparse_dropout(x,self.dropout,self.num_features_nonzero)
        elif training is not False:
            x = tf.nmn.dropout(x,self.dropout)
        
        supports = list()
        for i in range(len(support_)):
            if not self.featureless:
                pre_sup = dot(x,self.weight_[i],sparse=self.is_sparse_inputs)
            else:
                pre_sup = self.weights_[i]
            
            support = dot(support_[i],pre_sup,sparse = True)
            supports.append(support)
        
        output = tf.add_n(support)
        
        if self.bias:
            output += self.bias
        
        return self.activation(output)
        
            
        
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

SyntaxError: invalid syntax (<ipython-input-15-0aad010841a7>, line 23)

In [16]:
import  tensorflow as tf
from    tensorflow import keras
from    tensorflow.keras import layers, Sequential

class BasicBlock(layers.Layer):
    
    def __int__(self,filter_num,stride=1):
        super(BasicBlock,self).__init__()
        self.conv1 = layers.Conv2D
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-16-163f7d911e86>, line 6)

In [18]:
!conda install -c conda-forge jupytext --y


^C

CondaError: KeyboardInterrupt



In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import models,layers
tf.keras.backend.clear_session()
model = models.Sequential()
model.add(layers.Dense(20,activation='relu',input_shape=(15,)))
model.add(layers.Dense(10,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 20)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


In [ ]:
class CnnModel(model.Model):
    def __int__(self):
        super(CnnModel,self).__init__()
    def build(self,input_shape):
        self.embedding = layers.Embedding(MAX_WORD,7,input_length=MAX_LEN)
        self.conv_1 = layers.Conv1D(16,kernel_size = 5,name='conv_1',activation='relu')
        self.pool = layers.MaxPool1D()
        self.conv_2 = layers.Conv1D(128,kernel_size = 2,name='conv_2',activation = 'relu')
        self.flatten = layers.Flatten()
        self.dense = layers.Dense(1,activation='sigmoid')
        super(CnnModel,self).build(input_shape)
    
    def call(self,x):
        x = self.embedding(x)
        x = self.conv_1(x)
        x = self.pool(x)
        x = self.conv_2(x)
        x = self.pool(x)
        x = self.flatten(x)
        x = self.dense(x)
        return(x)

model = CnnModel()
model.build(input_shape=(None,MAX_LEN))
model.summary()
        
        
        

In [31]:
@tf.function
def strjoin(x,y):
    z =  tf.strings.join([x,y],separator = " ")
    tf.print(z)
    return z

import datetime
# 创建⽇日志
stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S") 
logdir = './data/autograph/%s' % stamp
writer = tf.summary.create_file_writer(logdir)
#开启autograph跟踪 tf.summary.trace_on(graph=True, profiler=True)
#执⾏行行autograph
result = strjoin("hello","world")
#将计算图信息写⼊入⽇日志
with writer.as_default():
    tf.summary.trace_export(
        name="autograph",
        step=0,
        profiler_outdir=logdir)


hello world


ValueError: Must enable trace before export.

In [32]:
x = tf.Variable(0.0,name = "x",dtype = tf.float32)
a = tf.constant(1.0)
b = tf.constant(-2.0)
c = tf.constant(1.0)
with tf.GradientTape() as tape:
    y = a*tf.pow(x,2) + b*x + c
dy_dx = tape.gradient(y,x)
print(dy_dx)

tf.Tensor(-2.0, shape=(), dtype=float32)


In [40]:
@tf.function
def f(x):
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    
    x = tf.cast(x,tf.float32)
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = a*tf.pow(x,2)+b*x+c
    dy_dx = tape.gradient(y,x)

    return ((dy_dx,y))
tf.print(f(tf.constant(0.0)))
tf.print(f(tf.constant(1.0)))

(-2, 1)
(0, 0)


In [ ]:
tf.Variable(0.0,name = 'x',dtype=tf.float32)

In [50]:
def f():
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    y = a*tf.pow(x,2)+b*x+c
    return(y)
optimizer = tf.keras.optimizers.SGD(learning_rate=1)
for _ in range(2):
    optimizer.minimize(f,[x])

tf.print(f(),x)

0 0.999998569


In [ ]:
def train(epoches):
    for epoch in tf.range(1,epoches+1):
        with tf.GradientTape() as tape:
            Y_hat = X@w + b
            loss = tf.squeeze(tf.transpose(Y-Y_hat)@(Y-Y_hat))/(2.0*n)
        dloss_dw,dloss_db = tape.gradient(loss,[w,b])
        w.assign(w - 0.001*dloss_dw)
        b.assign(b - 0.001*dloss_db)
        if epoch%1000 ==0:
            printbar()
            
        
        

In [ ]:
 
import tensorflow as tf
from tensorflow.keras import layers,losses,metrics,optimizers
#打印时间分割线 @tf.function def printbar():
    ts = tf.timestamp()
    today_ts = ts%(24*60*60)
    hour = tf.cast(today_ts//3600+8,tf.int32)%tf.constant(24)
    minite = tf.cast((today_ts%3600)//60,tf.int32)
    second = tf.cast(tf.floor(today_ts%60),tf.int32)
    def timeformat(m):
        if tf.strings.length(tf.strings.format("{}",m))==1:
            return(tf.strings.format("0{}",m))
        else:
            return(tf.strings.format("{}",m))
    timestring = tf.strings.join([timeformat(hour),timeformat(minite),
                timeformat(second)],separator = ":")
    tf.print("=========="*8,end = "")
    tf.print(timestring)

 
#样本数量量 n = 800
# ⽣生成测试⽤用数据集
X = tf.random.uniform([n,2],minval=-10,maxval=10)
w0 = tf.constant([[2.0],[-1.0]])
b0 = tf.constant(3.0)
Y = X@w0 + b0 + tf.random.normal([n,1],mean = 0.0,stddev= 2.0) # @表示矩阵乘法, 增加正态扰动
#构建输⼊入数据管道
ds = tf.data.Dataset.from_tensor_slices((X,Y)).shuffle(buffer_size = 1000).batch(100).prefetch(tf.data.experimental.AUTOTUNE)
#定义优化器器
optimizer = optimizers.SGD(learning_rate=0.001)
 
linear = layers.Dense(units = 1)
linear.build(input_shape = (2,))
@tf.function
def train(epoches):
    for epoch in tf.range(1,epoches+1):
    L = tf.constant(0.0) #使⽤用L记录loss值 for X_batch,Y_batch in ds:
        with tf.GradientTape() as tape:
            Y_hat = linear(X_batch)
            loss = losses.mean_squared_error(tf.reshape(Y_hat,[-1]),tf.reshape(Y_batch,[-1]))
        grads = tape.gradient(loss,linear.variables)
        optimizer.apply_gradients(zip(grads,linear.variables))
        L = loss
    if(epoch%100==0):
        printbar()
train(500)



In [2]:
a = tf.constant([1,2,3],dtype=tf.float32)

In [3]:
b = tf.range(1,10,delta=2)

In [4]:
d = tf.zeros([3,3])

In [2]:
t = tf.random.uniform([5,5],minval=0,maxval=10,dtype=tf.int32)

In [17]:
 scores = tf.random.uniform((4,10,7),minval=0,maxval=100,dtype=tf.int32)
tf.print(scores)

[[[87 70 14 ... 0 68 4]
  [7 87 86 ... 51 60 20]
  [59 71 82 ... 97 20 62]
  ...
  [13 48 17 ... 6 85 5]
  [65 62 34 ... 1 54 73]
  [19 83 52 ... 47 61 47]]

 [[25 44 63 ... 48 19 36]
  [47 12 68 ... 52 22 79]
  [62 29 19 ... 41 98 31]
  ...
  [78 92 93 ... 59 85 11]
  [88 5 33 ... 98 1 35]
  [31 14 3 ... 89 79 51]]

 [[45 90 68 ... 3 39 86]
  [30 59 66 ... 21 23 99]
  [10 42 36 ... 75 78 28]
  ...
  [61 91 60 ... 71 27 65]
  [1 32 44 ... 74 21 80]
  [23 85 99 ... 61 93 23]]

 [[87 7 35 ... 96 2 52]
  [60 92 14 ... 92 38 58]
  [37 90 28 ... 60 6 74]
  ...
  [96 45 49 ... 89 25 87]
  [55 77 37 ... 90 95 95]
  [1 30 1 ... 27 9 37]]]


In [24]:
tf.gather(scores,[0,5,9],axis=1)

<tf.Tensor: shape=(4, 3, 7), dtype=int32, numpy=
array([[[87, 70, 14, 78,  0, 68,  4],
        [42, 60, 22, 60, 90, 11, 14],
        [19, 83, 52, 72, 47, 61, 47]],

       [[25, 44, 63, 46, 48, 19, 36],
        [62,  4, 42, 70, 85,  4, 31],
        [31, 14,  3, 17, 89, 79, 51]],

       [[45, 90, 68, 60,  3, 39, 86],
        [62, 56, 22, 13,  4, 82, 62],
        [23, 85, 99, 57, 61, 93, 23]],

       [[87,  7, 35, 84, 96,  2, 52],
        [45, 77, 50, 25,  5, 97, 20],
        [ 1, 30,  1, 32, 27,  9, 37]]], dtype=int32)>

In [30]:
tf.gather_nd(scores,indices =[(0,0,1),(2,4,1),(3,6,3)])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([70, 43, 38], dtype=int32)>

In [34]:
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32) 
tf.print(c,"\n")

[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]] 



In [37]:
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)

In [38]:
tf.where(c>0,tf.fill(c.shape,np.nan),c)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1., nan, -1.],
       [nan, nan, -2.],
       [nan, -3., nan]], dtype=float32)>

In [39]:
tf.scatter_nd([[0,0],[2,1]],[c[0,0],c[2,1]],c.shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0., -3.,  0.]], dtype=float32)>

In [40]:
indices = tf.where(c<0)

In [41]:
indices

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 1]])>

In [42]:
tf.scatter_nd(indices,tf.gather_nd(c,indices),c.shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

In [46]:
tf.gather_nd(c,indices)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1., -1., -2., -3.], dtype=float32)>

In [51]:
tf.where(c<0,tf.fill(c.shape,tf.),c)

InvalidArgumentError: cannot compute SelectV2 as input #2(zero-based) was expected to be a int32 tensor but is a float tensor [Op:SelectV2]

In [52]:
 
a = tf.random.uniform(shape=[1,3,3,2],
                      minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

TensorShape([1, 3, 3, 2])


In [56]:
tf.reshape(a,[3,2,3])

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 48,  11, 126],
        [ 25,  83, 195]],

       [[ 30,  45, 110],
        [216,  59, 211]],

       [[194, 117,  26],
        [157,  19, 179]]], dtype=int32)>

In [57]:
a

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[ 48,  11],
         [126,  25],
         [ 83, 195]],

        [[ 30,  45],
         [110, 216],
         [ 59, 211]],

        [[194, 117],
         [ 26, 157],
         [ 19, 179]]]], dtype=int32)>

In [61]:
tf.expand_dims(a,axis=0)

<tf.Tensor: shape=(1, 1, 3, 3, 2), dtype=int32, numpy=
array([[[[[ 48,  11],
          [126,  25],
          [ 83, 195]],

         [[ 30,  45],
          [110, 216],
          [ 59, 211]],

         [[194, 117],
          [ 26, 157],
          [ 19, 179]]]]], dtype=int32)>

In [62]:
a = tf.random.uniform(shape=
[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

TensorShape([100, 600, 600, 4])


In [63]:
tf.transpose(a,perm=[3,1,2,0])

<tf.Tensor: shape=(4, 600, 600, 100), dtype=int32, numpy=
array([[[[  6, 127, 152, ...,  80,  64, 225],
         [204, 105,  61, ..., 125,  59, 177],
         [219, 135, 220, ...,  78, 171, 130],
         ...,
         [125,  19,   8, ...,  48, 114,  16],
         [ 83,  88, 187, ..., 124, 111,  83],
         [184, 237, 219, ...,  59, 198, 155]],

        [[ 91,  31,  22, ...,  33,  58, 188],
         [214,  80, 174, ...,  71, 143,  34],
         [ 44,  48, 141, ..., 223,  55, 110],
         ...,
         [124, 179, 135, ..., 184, 153,  51],
         [199, 173,  15, ..., 228, 235,  42],
         [ 73,  87,  52, ...,  21, 118,   1]],

        [[ 67,  58, 158, ..., 215, 233, 202],
         [101, 234, 108, ..., 134, 169, 120],
         [124, 105,  54, ...,  88,  81, 137],
         ...,
         [180, 167, 155, ..., 208,  58,  51],
         [248,  13, 228, ..., 130, 229,   4],
         [ 78, 163,  19, ...,  89,  96,  53]],

        ...,

        [[ 30, 223, 116, ..., 118, 155, 249],
      

In [65]:
a = tf.constant([[1.0,2],[-3,4.0]]) 
b = tf.constant([[5.0,6],[7.0,8.0]])
c = a+b

In [68]:
c**(0.5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.4494898, 2.828427 ],
       [2.       , 3.4641016]], dtype=float32)>

In [70]:
tf.sqrt(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.4494898, 2.828427 ],
       [2.       , 3.4641016]], dtype=float32)>

In [71]:
tf.reduce_sum(c,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([14., 16.], dtype=float32)>

In [72]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 4., 12.]], dtype=float32)>

In [75]:
a = tf.range(1,10) 
tf.print(tf.argmax(a)) 
tf.print(tf.argmin(a))

8
0


In [77]:
a = tf.constant([[1,2],[3,4]]) 
b = tf.constant([[2,0],[0,2]])

In [80]:
a = tf.constant([[1.0,2],[3.0,4]],dtype = tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [82]:
tf.broadcast_to(a,b.shape)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [87]:
tf.print(a.shape)

TensorShape([2, 2])


In [86]:
tf.print(tf.shape(a))

[2 2]


In [92]:
a*tf.constant(int(4))

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Mul] name: mul/

In [10]:
class DemoModule(tf.Module):
    def __init__(self,init_value=tf.constant(4.0),name=None):
        super(DemoModule,self).__init__(name=name)
        with self.name_scope:
            self.x = tf.Variable(init_value,dtype=tf.float32,trainable=True)
    @tf.function(input_signature=[tf.TensorSpec(shape=[],dtype=tf.float32)])
    def addprint(self,a):
        with self.name_scope:
            self.x.assign_add(a)
            tf.print(self.x)
            return(self.x)
        
            

In [11]:
demo = DemoModule()
result = demo.addprint(tf.constant(5.0))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
9


In [12]:
tf.print(result)

9


In [22]:
class DemoModule(tf.Module):
    def __init__(self,init_value=tf.constant(3.0,dtype=tf.float32),name=None):
        super(DemoModule,self).__init__(name=name)
        with self.name_scope:
            self.x = tf.Variable(init_value,dtype=tf.float32,trainable=True)
    @tf.function(input_signature=[tf.TensorSpec(shape=[],dtype=tf.float32)])
    def addprint(self,a):
        with self.name_scope:
            self.x.assign_add(a)
            tf.print(self.x)
            return(self.x)
        
            

In [23]:
demo = DemoModule()
result = demo.addprint(tf.constant(5.0))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
8


In [24]:
demo.variables

(<tf.Variable 'demo_module/Variable:0' shape=() dtype=float32, numpy=8.0>,)

In [25]:
demo.trainable_variables

(<tf.Variable 'demo_module/Variable:0' shape=() dtype=float32, numpy=8.0>,)

In [26]:
tf.saved_model.

()

In [ ]:
ds2 = tf.data.Dataset.from_tensor_slices((dfiris.to_dict()))

In [ ]:
 
tf.keras.backend.clear_session()
model = models.Sequential()
model.add(layers.Embedding(MAX_WORDS,7,input_length=MAX_LEN))
model.add(layers.Conv1D(filters = 64,kernel_size = 5,activation = "relu"))
model.add(layers.MaxPool1D(2))
model.add(layers.Conv1D(filters = 32,kernel_size = 3,activation = "relu"))
model.add(layers.MaxPool1D(2))
model.add(layers.Flatten())
model.add(layers.Dense(1,activation = "sigmoid"))
model.compile(optimizer='Nadam',
            loss='binary_crossentropy',
            metrics=['accuracy',"AUC"])
model.summary()

In [27]:
 
tf.keras.backend.clear_session()
inputs = layers.Input(shape=[MAX_LEN])
x  = layers.Embedding(MAX_WORDS,7)(inputs)
branch1 = layers.SeparableConv1D(64,3,activation="relu")(x)
branch1 = layers.MaxPool1D(3)(branch1)
branch1 = layers.SeparableConv1D(32,3,activation="relu")(branch1)
branch1 = layers.GlobalMaxPool1D()(branch1)
branch2 = layers.SeparableConv1D(64,5,activation="relu")(x)
branch2 = layers.MaxPool1D(5)(branch2)
branch2 = layers.SeparableConv1D(32,5,activation="relu")(branch2)
branch2 = layers.GlobalMaxPool1D()(branch2)
branch3 = layers.SeparableConv1D(64,7,activation="relu")(x)
branch3 = layers.MaxPool1D(7)(branch3)
branch3 = layers.SeparableConv1D(32,7,activation="relu")(branch3)
branch3 = layers.GlobalMaxPool1D()(branch3)
concat = layers.Concatenate()([branch1,branch2,branch3])
outputs = layers.Dense(1,activation = "sigmoid")(concat)
model = models.Model(inputs = inputs,outputs = outputs)
model.compile(optimizer='Nadam',
            loss='binary_crossentropy',
            metrics=['accuracy',"AUC"])
model.summary()
 

NameError: name 'MAX_LEN' is not defined

In [ ]:
class ResBlock(layers.Layer):
    def __init__(self, kernel_size, **kwargs):
        super(ResBlock, self).__init__(**kwargs)
        self.kernel_size = kernel_size
    def build(self,input_shape):
        self.conv1 = layers.Conv1D(filters=64,kernel_size=self.kernel_size,
                                   activation = "relu",padding="same")
        self.conv2 = layers.Conv1D(filters=32,kernel_size=self.kernel_size,
                                   activation = "relu",padding="same")
        self.conv3 = layers.Conv1D(filters=input_shape[-1],
                           kernel_size=self.kernel_size,activation =
self.maxpool = layers.MaxPool1D(2)
"relu",padding="same")
super(ResBlock,self).build(input_shape) # 相当于设置self.built = True
    def call(self, inputs):
        x = self.conv1(inputs)
        x = self.conv2(x)
        x = self.conv3(x)
        x = layers.Add()([inputs,x])
        x = self.maxpool(x)
        return x
#如果要让⾃自定义的Layer通过Functional API 组合成模型时可以序列列化，需要⾃自定义 get_config⽅方法。
    def get_config(self):
        config = super(ResBlock, self).get_config()
        config.update({'kernel_size': self.kernel_size})
        return config

In [96]:
import pandas as pd
boohee_food_df = pd.read_csv('/Users/wjj/Desktop/食谱生成/soylent-recipes-master/data/usda_nutrient_db_sr28/boobee_food_8.csv')


In [101]:
df_1 = boohee_food_df[boohee_food_df.food_id.isin([19588])][['Energy from: carbohydrate','Energy from: fat','Energy from: protein']]
df_2 = boohee_food_df[boohee_food_df.food_id.isin([119])]

In [102]:
df_1*(190/50)+df_2*(300/50)

TypeError: can't multiply sequence by non-int of type 'float'

In [100]:
300*0.85

food_id  salt  sugar    oil  vegatable_weight  starch_energy  is_liquid  \
2163    19588   0.0    0.0  1.866             1.866        218.739          0   
3350      119   0.0    0.0  0.000             0.000          0.000          1   

      energy  protein  carbohydrate  ...  meat_egg_exchange  \
2163  133.05     5.57         21.14  ...               0.16   
3350   15.50     1.50          0.60  ...               0.00   

      vegetable_exchange  oil_exchange  fruit_exchange  nuts_exchange  \
2163                 0.0           0.1             0.0            0.0   
3350                 0.0           0.0             0.0            0.0   

      dairy_exchange  soy_exchange  Energy from: carbohydrate  \
2163             0.0          0.00                      84.58   
3350             0.0          0.17                       2.40   

      Energy from: fat  Energy from: protein  
2163             28.08                 22.28  
3350              7.20                  6.00  

[2 rows x 53 columns]

In [126]:
{'score': 85, 'desc': ['食谱热量合适(30分)', '三餐热量合适(10分)', '三大营养素符合目标对应的推荐范围(40分)', '日均食物种类超过12种(20分)', '蔬菜 < 300g(-15)']}

{'user_id': 'dbe0f3bd-1df2-4280-96dc-f70cba88ccc6', 'meal': [{'meal_time': 1, 'foods': [{'food_id': 119, 'amount': '255g'}, {'food_id': 19588, 'amount': '160g'}]}, {'meal_time': 2, 'foods': [{'food_id': 9447, 'amount': '200g'}, {'food_id': 12641, 'amount': '50g'}, {'food_id': 25914, 'amount': '100g'}, {'food_id': 15943, 'amount': '0g'}, {'food_id': 62954, 'amount': '0g'}, {'food_id': 56, 'amount': '150g'}]}, {'meal_time': 3, 'foods': [{'food_id': 20506, 'amount': '150g'}, {'food_id': 17127, 'amount': '0g'}, {'food_id': 5206, 'amount': '200g'}, {'food_id': 15219, 'amount': '0g'}, {'food_id': 25914, 'amount': '50g'}, {'food_id': 56, 'amount': '150g'}]}]}

[{'meal_time': 1, 'foods': [{'food_id': 119, 'amount': '255g'}, {'food_id': 19588, 'amount': '160g'}]}, {'meal_time': 2, 'foods': [{'food_id': 9447, 'amount': '200g'}, {'food_id': 12641, 'amount': '50g'}, {'food_id': 25914, 'amount': '100g'}, {'food_id': 15943, 'amount': '0g'}, {'food_id': 62954, 'amount': '0g'}, {'food_id': 56, 'amount': '150g'}]}, {'meal_time': 3, 'foods': [{'food_id': 20506, 'amount': '150g'}, {'food_id': 17127, 'amount': '0g'}, {'food_id': 5206, 'amount': '200g'}, {'food_id': 15219, 'amount': '0g'}, {'food_id': 25914, 'amount': '50g'}, {'food_id': 56, 'amount': '150g'}]}]


161.5

In [127]:
0.933*(160/50)+4.766*4+48.003+47.368*2+38.263*3+0.467*4+47.368


328.81359999999995

In [104]:
2.40*6+84.58*(190/50)

335.804

In [105]:
7.2*6+28.08*(190/50)

149.904

In [106]:
6*6+22.28*(190/50)

120.664

In [107]:
15.50*6+133.05*(190/50)

598.59

In [108]:
335.804/598.59

0.5609916637431296

In [109]:
149.904/598.59

0.2504285069914298

In [110]:
120.664/598.59

0.20158038056098498

In [114]:
561+201+250

1012

In [117]:
598.59*0.85/1800

0.2826675

In [67]:
pd.read_csv('/Users/wjj/Downloads/meal_evaluation41.csv',sep='/t', encoding = 'gb2312')

/Users/wjj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


UnicodeDecodeError: 'gb2312' codec can't decode byte 0xb1 in position 5: illegal multibyte sequence

In [83]:
old_score_dict = {'de2c78c5-b386-47ed-b727-050ebf561261':52.8,
 '00f63b25-9c53-4178-a7ac-48f57eea49c1':42.1,
 '390e61f0-5528-4324-ac9f-50ced9ec2811':49.3,
 '45774286-308e-46da-a13f-33fb789c8179':44.3,
 '4c21afb3-9a32-4d31-b8de-936795382854':51.25,
 '4deceb10-d570-4318-909b-b2c6d16ee5fd':47.1,
 '52f50059-94d0-488f-8b09-d34a9011663b':50.7,
 '64951fac-339b-404b-8cc7-22efa7761e09':35,
 '76849a21-21b0-44a2-b522-5022acc5a054':55,
 '7fc86219-891e-4292-9411-0d0b630de5be':43.6,
 '8eba042f-4efa-429b-ab10-30262d78b36f':56.4,
 'a7fa3cad-180f-4964-90f9-0f7cf8a9e5b0':50.7,
 'b3eba015-b76d-490e-8694-3018a07fae1e':51.4,
 'c1c0ce80-0c9d-4399-9cd5-b224c69055ea':51.3,
 'c8ce9144-0586-4b48-b61e-d7b8e788c60e':5,
 'c9e9d7c3-e337-4e36-bb25-3736d39f09e9':35,
 'f77c7ad7-3058-4508-bb00-defdfcf3dd92':47.9,
 'f9fa7f3f-6e66-4267-a16b-c71d15ae8630':42.9,
'4d2ff353-0a14-4ede-9550-8d21cdc20f08':56.4
 }

In [89]:
import pickle
with open('/Users/wjj/Desktop/已生成食谱/7/score_dict.pk', 'rb') as f:
    score_dict = pickle.load(f)

In [91]:
len(score_dict)

100

In [95]:
15/19

0.7894736842105263

In [ ]:
class _Conv(Layer):
    """Abstract nD convolution layer (private, used as implementation base).

    ### 函数说明

    # Arguments
        rank: An integer, the rank of the convolution,
            e.g. "2" for 2D convolution.
        filters: Integer, the dimensionality of the output space
            (i.e. the number of output filters in the convolution).
        kernel_size: An integer or tuple/list of n integers, specifying the
            dimensions of the convolution window.
        #### 参数注释
    """

    def __init__(self, rank,
                 filters,
                 kernel_size,
                 strides=1,
                 padding='valid',
                 data_format=None,
                 dilation_rate=1,
                 activation=None,
                 use_bias=True,
                 kernel_initializer='glorot_uniform',
                 bias_initializer='zeros',
                 kernel_regularizer=None,
                 bias_regularizer=None,
                 activity_regularizer=None,
                 kernel_constraint=None,
                 bias_constraint=None,
                 **kwargs):
        super(_Conv, self).__init__(**kwargs)
        self.rank = rank
        self.filters = filters
        self.kernel_size = conv_utils.normalize_tuple(kernel_size, rank,
                                                      'kernel_size')
        self.strides = conv_utils.normalize_tuple(strides, rank, 'strides')
        self.padding = conv_utils.normalize_padding(padding)
        ### 初始化参数

def build(self,input_shape):
    if self.data_format == 'channels_first':
        channel_axis = 1
    else:
        channel_axis = -1
    if intput_shape[channel_axis] is None:
        raise ValueError('The channel dimension of the inputs '
                             'should be defined. Found `None`.')
    input_dim = input_shape[channel_axis]
    
    kernel_shape = self.kernel_size+(input_dim,self.filter)
    self.kernel = self.add_weight(shape=kernel_shape,initializer=self.kernel_initializer,
                                 name='kernel',
                                 regularizer=self.kernel_regularizer,
                                 constraint=self.kernel_constraint,
                                 )
    if self.use_bias:
        self.bias = self.add_weight(shape=(self.filter,),
                               initializer=self.bias_initializer,
                               name='kernel',
                               regularizer=self.bias_regularizer,
                               constraint = self.bias_constraint)
    else:
        self.bias = None
        
    self.input_spec = InputSpec(ndim=self.rank+2,
                               axis ={channel_axis:input_dim})
    self.built = True
    
def call(self,inputs):
    output = K.dot(inputs,self.kernel)
    if self.use_bias:
        output = K.bias_add(output,self.bias,data_format='channel_last')
    if self.activation is not None:
        output = self.activation(output)
    return output

def compute_output_shape(self,input_shape):
    assert input_shape and len(input_shape) >= 2
    assert input_shape[-1]
    output_shape = list(input_shape)
    output_shape[-1] = self.units
    return tuple(output_shape)

def get_config(self):
    config = {
        'units': self.units,
        'activation': activations.serialize(self.activation),
        ###配置信息，省略
    }
    base_config = super(Dense, self).get_config()
    return dict(list(base_config.items()) + list(config.items()))



        
    
    
    
    
    
    
    
    

In [137]:
def call(self,inputs):
    if self.rank==1:
        outputs = K.conv1d(
            inputs,
            self.kernel,
            setrides = self.setrides,
            padding = self.padding,
            data_format =self.data_format,
            dilation_rate = self.dilation_rate[0],
            
                )
    if self.rank==2:
         outputs = K.conv2d(
                inputs,
                self.kernel,
                strides=self.strides,
                padding=self.padding,
                data_format=self.data_format,
                dilation_rate=self.dilation_rate)
    if self.rank == 3:
        outputs = K.conv3d(
                inputs,
                self.kernel,
                strides=self.strides,
                padding=self.padding,
                data_format=self.data_format,
                dilation_rate=self.dilation_rate)

    if self.use_bias:
        outputs = K.bias_add(
                outputs,
                self.bias,
                data_format = self.data_format
                
                )
    if self.activation is not None:
        return self.activation(outputs)
    
    return outputs


    

In [ ]:
class MyDense(layers.Layer):
    def __init__(self,units=32):
        super(MyDense,self).__init__()
        self.units = units
    def build(self,input_shape):
        self.w = self.add_weight(shape=(input_shape[-1],self.units),
                                initializer='random_normal',
                                trainable=True
                                )
        self.b = self.add_weight(shape=(self.units,),
                                initializer='random_normal',
                                trainable = True,
                                )
    def call(self,inputs):
        return tf.matmul(input,self.w)+self.b
    
    def get_config(self):
        return {'unit':self.units}

inputs = keras.Input((4,))
outputs = MyDense(10)(inputs)
outputs = keras.Model(inputs,outputs)
new_model = model.get_config()
